SMS/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('adminapp.urls')),
    path('facultyapp/',include('facultyapp.urls',namespace='facultyapp')),
    path('studentapp/',include('studentapp.urls',namespace='studentapp')),
]
# namespace is used to communicate inn b/w apps

facultyapp/urls.py
from django.urls import path,include
from . import views
app_name = 'facultyapp'

urlpatterns = [
    path('FacultyHomePage/', views.FacultyHomePage, name='FacultyHomePage'),
    path('add_blog/', views.add_blog, name='add_blog'),
    path('<int:pk>/delete/', views.delete_task, name='delete'),
    path('add_course/', views.add_course, name='add_course'),
    path('view_student_list/', views.view_student_list, name='view_student_list'),
    path('post_marks/',views.post_marks,name = 'post_marks'),

]

studentapp/urls.py
from django.urls import path, include
from . import views
app_name = 'studentapp'

urlpatterns = [
    path('StudentHomePage/', views.StudentHomePage, name='StudentHomePage'),
]

templates/Navbar/FacultyNavbar.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
            <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'facultyapp:FacultyHomePage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'facultyapp:add_blog' %}">blog</a>
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_course' %}">ADD Course</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:view_student_list' %}">View student</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:post_marks' %}">Post Marks</a>
        </li>
        <li class="nav-item">
          <form class="d-flex ms-auto" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </li>
      </ul>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}"><b><i>Logout</i></b></a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}

</body>
</html>

templates/Navbar/ProjectNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <style>
        /* Custom dark purple background color */
        .bg-dark-purple {
            background-color: #4B0082; /* Dark purple color */
            color: #ffffff; /* White text color for contrast */
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark-purple">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'projecthomepage' %}"><b>SMS</b></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add_studentpagecall' %}"><b>Add Student</b></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <b><i>PFSD Concepts</i></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
                            <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">Exception</a></li>
                            <li><a class="dropdown-item" href="{% url 'randompagecall' %}">OTP</a></li>
                            <li><a class="dropdown-item" href="{% url 'calculatorpagecall' %}">Calculator</a></li>
                            <li><a class="dropdown-item" href="{% url 'add_task' %}">TO DO List</a></li>
                            <li><a class="dropdown-item" href="{% url 'datetimepagecall' %}">DATETIME</a></li>
                            <li><a class="dropdown-item" href="{% url 'upload_file' %}">Pie Chart</a></li>
                            <li><a class="dropdown-item" href="{% url 'submit_feedback' %}">Feedback</a></li>
                            <li><a class="dropdown-item" href="{% url 'add_contact' %}">Contact Manager</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <ul class="navbar-nav ms-auto">
                <li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="nav-link">Welcome, {{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'UserRegisterPageCall' %}"><b>Register</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'UserLoginPageCall' %}"><b>Login</b></a>
                    </li>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

templates/Navbar/StudentNavbar.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'studentapp:StudentHomePage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>

      </ul>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}"><b><i>Logout</i></b></a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
</nav>
{% block body %}

{% endblock %}

</body>
</html>